/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SaftyRouteImport } from './routes/safty'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiMcpRouteImport } from './routes/api/mcp'
import { Route as ApiPublicProxyRouteImport } from './routes/api/public/proxy'
import { Route as ApiPublicSplatRouteImport } from './routes/api/public/$'

const SaftyRoute = SaftyRouteImport.update({
  id: '/safty',
  path: '/safty',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpRoute = ApiMcpRouteImport.update({
  id: '/api/mcp',
  path: '/api/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicProxyRoute = ApiPublicProxyRouteImport.update({
  id: '/api/public/proxy',
  path: '/api/public/proxy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSplatRoute = ApiPublicSplatRouteImport.update({
  id: '/api/public/$',
  path: '/api/public/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/safty': typeof SaftyRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/public/$': typeof ApiPublicSplatRoute
  '/api/public/proxy': typeof ApiPublicProxyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/safty': typeof SaftyRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/public/$': typeof ApiPublicSplatRoute
  '/api/public/proxy': typeof ApiPublicProxyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/safty': typeof SaftyRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/public/$': typeof ApiPublicSplatRoute
  '/api/public/proxy': typeof ApiPublicProxyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/safty' | '/api/mcp' | '/api/public/$' | '/api/public/proxy'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/safty' | '/api/mcp' | '/api/public/$' | '/api/public/proxy'
  id:
    | '__root__'
    | '/'
    | '/safty'
    | '/api/mcp'
    | '/api/public/$'
    | '/api/public/proxy'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SaftyRoute: typeof SaftyRoute
  ApiMcpRoute: typeof ApiMcpRoute
  ApiPublicSplatRoute: typeof ApiPublicSplatRoute
  ApiPublicProxyRoute: typeof ApiPublicProxyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/safty': {
      id: '/safty'
      path: '/safty'
      fullPath: '/safty'
      preLoaderRoute: typeof SaftyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp': {
      id: '/api/mcp'
      path: '/api/mcp'
      fullPath: '/api/mcp'
      preLoaderRoute: typeof ApiMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/proxy': {
      id: '/api/public/proxy'
      path: '/api/public/proxy'
      fullPath: '/api/public/proxy'
      preLoaderRoute: typeof ApiPublicProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/$': {
      id: '/api/public/$'
      path: '/api/public/$'
      fullPath: '/api/public/$'
      preLoaderRoute: typeof ApiPublicSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SaftyRoute: SaftyRoute,
  ApiMcpRoute: ApiMcpRoute,
  ApiPublicSplatRoute: ApiPublicSplatRoute,
  ApiPublicProxyRoute: ApiPublicProxyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
